
* Introduction

Many of the Nordic national libraries for accessible literature and
publishing distribute their books in the form of EPUB3. This contains
a CSS that aims to render the content in an way so that it is as
accessible as possible.

* Goal

The goal of this repository is to create a common CSS that
incorporates all the best practices.

* Guidelines for accessible CSS

The [[https://sbsdev.github.io/nordic-accessible-epub-css/][guidelines]] explain why an accessible CSS is needed and provide
general guidance for what said CSS needs to cater for.

* Samples

There are some CSS files in the samples folder

- [[https://github.com/sbsdev/nordic-accessible-epub-css/blob/main/samples/mtm.css][mtm.css]] is from a sample book from MTM. This css has been enhanced
  to comply with the guidelines
- [[https://github.com/sbsdev/nordic-accessible-epub-css/blob/main/samples/sbs.css][sbs.css]] is the CSS that is included in all the ebooks produced by SBS
- [[https://github.com/sbsdev/nordic-accessible-epub-css/blob/main/samples/epub3-to-daisy202.css][epub3-to-daisy202.css]] is from the DAISY pipeline

* Build

The source of the guidelines is kept in an [[https://orgmode.org/][org-mode]] file which is the
exported (via the org-mode export facilities) to a markdown file. This
file is then enhanced with meta data information (author, date,
version) and placed in the =docs= folder from where the github pages
process picks up and publishes the document as html.
